import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'quill/dist/quill.snow.css'; // ตรวจสอบ path อีกครั้ง

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Report Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Sarabun&family=Sofia&family=Slabo+27px&family=Roboto&family=Inconsolata&family=Ubuntu&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${inter.className}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
